const totalAvaliableCity = [
    { label: "Ahtet Min Hla (အထက်မင်းလှ)", id: 1 },
    { label: "Ann (အမ်း)", id: 1 },
    { label: "AungLan (အောင်လံ)", id: 2 },
    { label: "AungPan (အောင်ပန်း)", id: 3 },
    { label: "AyarDaw (အရာတော်)", id: 4 },
    { label: "AyeTharYar (အေးသာယာ)", id: 5 },
    { label: "Bagan / Naung-U (ပုဂံ / ညောင်ဦး)", id: 6 },
    { label: "Bago (ပဲခူး)", id: 7 },
    { label: "Bahin (ဗဟင်း)", id: 8 },
    { label: "BanMauk (ဗန်းမောက်)", id: 9 },
    { label: "Bhamo (ဗန်းမော်)", id: 10 },
    { label: "Bilin (ဘီးလင်း)", id: 11 },
    { label: "BokPyin (ဘုတ်ပြင်း)", id: 12 },
    { label: "Budalin (ဘုတလင်)", id: 13 },
    { label: "Chauk (ချောက်)", id: 14 },
    { label: "Chaung Tha (ချောင်းသာ)", id: 15 },
    { label: "Chaung U ()", id: 16 },
    { label: "Chaungzon ()", id: 17 },
    { label: "DagonAyar(Yangon) ()", id: 18 },
    { label: "Daik-U ()", id: 19 },
    { label: "Danai ()", id: 20 },
    { label: "Danubyu ()", id: 21 },
    { label: "Dawei ()", id: 22 },
    { label: "Demoso ()", id: 23 },
    { label: "Gangaw ()", id: 24 },
    { label: "Gwa ()", id: 25 },
    { label: "Gaway Gone ()", id: 26 },
    { label: "Gyeik Taw ()", id: 27 },
    { label: "GyoBinGauk ()", id: 28 },
    { label: "Hakha ()", id: 29 },
    { label: "Ham Myint Mo ()", id: 30 },
    { label: "HeHoe ()", id: 31 },
    { label: "Hinthada ()", id: 32 },
    { label: "Hlegu ()", id: 33 },
    { label: "Hopin ()", id: 34 },
    { label: "Hopong ()", id: 35 },
    { label: "Hpa-An ()", id: 36 },
    { label: "Hpakan ()", id: 37 },
    { label: "Hpayargyi ()", id: 38 },
    { label: "Hseni ()", id: 39 },
    { label: "Hsipaw ()", id: 40 },
    { label: "HtoneBo ()", id: 41 },
    { label: "Indaw ()", id: 42 },
    { label: "Ingapu ()", id: 43 },
    { label: "Inn Ta Kaw ()", id: 44 },
    { label: "Inn Ma ()", id: 45 },
    { label: "Kalaw ()", id: 46 },
    { label: "Kale ()", id: 47 },
    { label: "Kalewa ()", id: 48 },
    { label: "Kamma ()", id: 49 },
    { label: "Kambalu ()", id: 50 },
    { label: "KanBya ()", id: 51 },
    { label: "Kanpetlet ()", id: 52 },
    { label: "Katha ()", id: 53 },
    { label: "KawKaReik ()", id: 54 },
    { label: "KawThaung ()", id: 55 },
    { label: "KayTuMadi ()", id: 56 },
    { label: "Keng Tung ()", id: 57 },
    { label: "Khin-U ()", id: 58 },
    { label: "Kho Lam ()", id: 59 },
    { label: "Koebin ()", id: 60 },
    { label: "Kon Zaung ()", id: 61 },
    { label: "Kume ()", id: 62 },
    { label: "Kutkai ()", id: 63 },
    { label: "Kwin Hla ()", id: 64 },
    { label: "KyaikKami ()", id: 65 },
    { label: "KyaInSeikGyi ()", id: 66 },
    { label: "Kyangin ()", id: 67 },
    { label: "Kyauk Gyi ()", id: 68 },
    { label: "KyaukMe ()", id: 69 },
    { label: "KyaukPaDaung ()", id: 70 },
    { label: "Kyauk Phyu ()", id: 71 },
    { label: "KyaukSe ()", id: 72 },
    { label: "KyaukTaGar ()", id: 73 },
    { label: "KyaukTaw ()", id: 74 },
    { label: "KyaungTawYar ()", id: 75 },
    { label: "Kyaw ()", id: 76 },
    { label: "Kyeintali ()", id: 77 },
    { label: "Kyun Hla ()", id: 78 },
    { label: "Kyun Chaung ()", id: 79 },
    { label: "Lashio ()", id: 80 },
    { label: "Lat Yin Ma ()", id: 81 },
    { label: "Laukkaing ()", id: 82 },
    { label: "Lawksawk ()", id: 83 },
    { label: "Lay Taung ()", id: 84 },
    { label: "Lay Tine Sin ()", id: 85 },
    { label: "Letpadan ()", id: 86 },
    { label: "Letpanhla ()", id: 87 },
    { label: "Lewe ()", id: 88 },
    { label: "Loikaw ()", id: 89 },
    { label: "Loilem ()", id: 90 },
    { label: "Lonkin ()", id: 91 },
    { label: "Ma-ei ()", id: 92 },
    { label: "Mabein ()", id: 93 },
    { label: "Madaya ()", id: 94 },
    { label: "Magway ()", id: 95 },
    { label: "Mahar Myaing ()", id: 96 },
    { label: "Mahlaing ()", id: 97 },
    { label: "Malun ()", id: 98 },
    { label: "Mandalay ()", id: 99 },
    { label: "Maubin ()", id: 100 },
    { label: "Maw Hun ()", id: 101 },
    { label: "Maw Luu ()", id: 102 },
    { label: "Mawlamyine ()", id: 103 },
    { label: "Me Za Li Kone ()", id: 104 },
    { label: "Meiktila ()", id: 105 },
    { label: "Migyaungye ()", id: 106 },
    { label: "MinBya ()", id: 107 },
    { label: "Minbu ()", id: 108 },
    { label: "Moebyel ()", id: 109 },
    { label: "Mogaung ()", id: 110 },
    { label: "Mogok ()", id: 111 },
    { label: "Mohnyin ()", id: 112 },
    { label: "Mong Hsu ()", id: 113 },
    { label: "Mongmit ()", id: 114 },
    { label: "Monywa ()", id: 115 },
    { label: "Mrauk-U ()", id: 116 },
    { label: "Mudon ()", id: 117 },
    { label: "Muse ()", id: 118 },
    { label: "Mya Taung ()", id: 119 },
    { label: "Myaing ()", id: 120 },
    { label: "Myanaung ()", id: 121 },
    { label: "Myaungmya ()", id: 122 },
    { label: "Myawaddy ()", id: 123 },
    { label: "Myeik ()", id: 124 },
    { label: "Myingyan ()", id: 125 },
    { label: "Myitchay ()", id: 126 },
    { label: "Myitkyina ()", id: 127 },
    { label: "Myitnge ()", id: 128 },
    { label: "Myittha ()", id: 129 },
    { label: "Myo Hla ()", id: 130 },
    { label: "Myo Gyi ()", id: 131 },
    { label: "Myogyi ()", id: 132 },
    { label: "Namhkan ()", id: 133 },
    { label: "Namsang ()", id: 134 },
    { label: "Namsi Awng ()", id: 135 },
    { label: "Nan Mar ()", id: 136 },
    { label: "Nanmati ()", id: 137 },
    { label: "Natmauk ()", id: 138 },
    { label: "Natogyi ()", id: 139 },
    { label: "Nattalin ()", id: 140 },
    { label: "Naungtayar ()", id: 141 },
    { label: "Nawnghkio ()", id: 142 },
    { label: "Naypyitaw ()", id: 143 },
    { label: "Ngapali ()", id: 144 },
    { label: "Ngar O ()", id: 145 },
    { label: "Ngwe Saung ()", id: 146 },
    { label: "Nyaung Chay Htauk ()", id: 147 },
    { label: "Nyaung Kone ()", id: 148 },
    { label: "Nyaung Lay Pin ()", id: 149 },
    { label: "Nyaung Pin Thar ()", id: 150 },
    { label: "Nyaung Shwe( Inle ) ()", id: 151 },
    { label: "NyaungPin ()", id: 152 },
    { label: "Nyaungdon ()", id: 153 },
    { label: "Oak Pho ()", id: 154 },
    { label: "Oke Shit Pin ()", id: 155 },
    { label: "Oktwin ()", id: 156 },
    { label: "Padaung ()", id: 157 },
    { label: "Padein ()", id: 158 },
    { label: "Padigon ()", id: 159 },
    { label: "Pakokku ()", id: 160 },



    // { label: " ()", id: 77 },
    

    
    { label: "MuSe ()", id: 199 },
    { label: "Yangon ()", id: 200 },
  ];


export default totalAvaliableCity